name: Build and test

on:
  pull_request:
  push:
    branches:
      - main
      - staging
      - trying
  schedule:
    - cron: '0 0 * * 6'

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    # these tests based on the nightly compiler, which can be broken
    # consequently, we continue on an error
    #continue-on-error: true

    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            rust: 'stable'
            targets: 'x86_64-unknown-linux-gnu'

    steps:
    - uses: hecrj/setup-rust-action@v1
      with: 
         rust-version: ${{ matrix.rust }}
         components: ${{ matrix.components || '' }}
         targets: ${{ matrix.targets || '' }}
    - uses: actions/checkout@v2
      with:
         lfs: true
    - name: Check Cargo availability
      run: cargo --version
    - name: Building runh
      run:
         cargo build
    - name: Pull container image
      run: |
         mkdir -p data/rootfs
         sudo target/debug/runh -l debug pull -b data/rootfs/ registry.git.rwth-aachen.de/acs/public/hermitcore/rusty-hermit/demo
    - name: Create container specification
      run: |
         target/debug/runh -l debug spec --bundle data/
         sed -i 's;"sh";"/hermit/rusty_demo";' data/config.json
    - name: Create container
      run:
         sudo target/debug/runh -l debug create -b data hello
    - name: Start container
      run:
         sudo target/debug/runh -l debug start hello
    - name: Delete container
      run:
         sudo target/debug/runh -l debug delete hello
